"""empty message

Revision ID: 8708647d4499
Revises: aba077d5f7e1
Create Date: 2024-11-15 23:03:37.462149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8708647d4499'
down_revision = 'aba077d5f7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('apellido', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ciudad')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
